data_dir: ../ts_quantum/datasets
dataset: etth1
horizon: 720
lookback: 720
model:
  qmix_layers: 2
  qmix_norm: softmax
  head_agg: false
  spectrum_inject: false
  d_token: 512
  entangle_topo: linear
  kernel_fn: quantum
  n_layers: 2
  n_qubits: 8
  revin_affine: true
  spectrum_M: 32
  spectrum_amp_normalize: false
  spectrum_freq_align: true
  spectrum_range: '0_2'
  spectrum_time_align: true
  theta_S_scale0: 0.5
  use_H: true
  use_S: true
  use_fmap: true
  use_periodic_feat: true
  use_spectrum: true
run_name: qm_qmix_soft_etth1_720_2024
save_dir: /home/wuyoujun/qcc-mamba/results/qmix
seed: 2024
train:
  accumulation_steps: 1
  batch_size: 32
  epochs: 50
  eval_test_every_epoch: false
  lr: 0.0001
  num_workers: 0
  patience: 8
  proj_weight_decay: 0.0
  stride: 1
  use_amp: false
  weight_decay: 1.0e-05
